fn main() {
    // generated by `sqlx migrate build-script`
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");
    // build tauri app
    tauri_build::build()
}
